FROM nvcr.io/nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04
WORKDIR /opt
ENV DEBIAN_FRONTEND noninteractive

RUN \
    apt-get update        &&   \
    apt-get install --yes      \
        build-essential autoconf cmake flex bison zlib1g-dev \
        fftw-dev fftw3 apbs libicu-dev libbz2-dev libgmp-dev \
        bc libblas-dev liblapack-dev git libtool swig uuid-dev \
        libfftw3-dev automake lsb-core libxc-dev libgsl-dev  \
        unzip libhdf5-serial-dev ffmpeg libcurl4-openssl-dev \
        libedit-dev libyaml-cpp-dev make libquadmath0 gfortran \
        python3-yaml automake pkg-config libc6-dev libzmq3-dev \
        libjansson-dev liblz4-dev libarchive-dev python3-pip \
        libsqlite3-dev lua5.1 liblua5.1-dev lua-posix jq     \
        python3-dev python3-cffi python3-ply python3-sphinx  \
        aspell aspell-en valgrind libyaml-cpp-dev wget vim   \
        make libzmq3-dev python3-yaml time valgrind  libeigen3-dev \
        mlocate python3-jsonschema python-is-python3       &&\
    apt-get clean all


WORKDIR /opt
ARG mpich=4.2.2
ARG mpich_prefix=mpich-$mpich
RUN \
    wget https://www.mpich.org/static/downloads/$mpich/$mpich_prefix.tar.gz && \
    tar xvzf $mpich_prefix.tar.gz                                           && \
    cd $mpich_prefix                                                        && \
    ./configure FFLAGS=-fallow-argument-mismatch FCFLAGS=-fallow-argument-mismatch \
    --prefix=/opt/mpich/install                                             && \
    make -j 16                                                              && \
    make install                                                            && \
    make clean                                                              && \
    cd ..                                                                   && \
    rm -rf $mpich_prefix.tar.gz
ENV PATH=$PATH:/opt/mpich/install/bin
ENV PATH=$PATH:/opt/mpich/install/include
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/mpich/install/lib
RUN /sbin/ldconfig

ENV PATH=$PATH:/usr/local/cuda/lib64/stubs
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64/stubs
ENV PATH=$PATH:/usr/local/cuda-11.8/targets/x86_64-linux/lib/stubs
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.8/targets/x86_64-linux/lib/stubs

RUN ln -s /usr/local/cuda-11.8/targets/x86_64-linux/lib/stubs/libnvidia-ml.so /usr/local/cuda-11.8/targets/x86_64-linux/lib/stubs/libnvidia-ml.so.1 


RUN pip install setuptools
RUN python -m pip install mpi4py -i https://pypi.anaconda.org/mpi4py/simple
RUN python -m pip install tblite
RUN python -m pip install --prefer-binary pyscf
RUN python -m pip install gpu4pyscf-cuda11x
RUN python -m pip install cutensor-cu11
RUN python -m pip install tensorflow[and-cuda]
RUN python -m pip install papermill
RUN python -m pip install tqdm
RUN python -m pip install py3DMol
RUN python -m pip install pandas
RUN python -m pip install b2[full]
RUN python -m pip install ply
RUN python -m pip install pyyaml
#RUN python -m pip install openbabel-wheel


# Install Boost
WORKDIR /opt
RUN wget 'https://sourceforge.net/projects/boost/files/boost/1.87.0/boost_1_87_0.zip'
RUN unzip boost_1_87_0.zip
RUN mv boost_1_87_0 boost
RUN cd /opt/boost                                                           && \
    ./bootstrap.sh                                                          && \
    ./b2 install


#Install HWLOC
WORKDIR /opt
RUN git clone -b v2.11 https://github.com/open-mpi/hwloc.git hwloc          && \
    cd hwloc                                                                && \
    ./autogen.sh                                                            && \
    ./configure                                                             && \
    make -j 16                                                              && \
    make install 


# Install flux-core
WORKDIR /opt
RUN git clone -b v0.69.0 https://github.com/flux-framework/flux-core.git    && \
    cd flux-core                                                            && \
    ./autogen.sh                                                            && \
    ./configure                                                             && \
    make -j 1                                                              && \ 
    make install
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
ENV LD_RUN_PATH=$LD_RUN_PATH:/usr/local/lib


# Install flux-sched
WORKDIR /opt
RUN git clone -b v0.36.0 https://github.com/flux-framework/flux-sched.git   && \
    cd flux-sched                                                           && \
    cmake -B build                                                          && \
    cmake --build build                                                     && \
    cmake --build build -t install                                          


# Install Open Babel
WORKDIR /opt
RUN git clone -b openbabel-3-1-1 https://github.com/openbabel/openbabel.git            
RUN git clone https://github.com/conda-forge/openbabel-feedstock.git obf
RUN cd /opt/openbabel                                                       && \
    mkdir build                                                             && \
    cd build                                                                && \
    cmake .. -DCMAKE_INSTALL_PREFIX=/opt/openbabel/install -DBUILD_GUI=ON      \
             -DCMAKE_BUILD_TYPE=Release -DWITH_INCHI=ON                        \
             -DPYTHON_BINDINGS=ON -DRUN_SWIG=ON                             && \
    make -j 2                                                               && \
    make install 
ENV PYTHONPATH=$PYTHONPATH:/opt/openbabel
ENV PYTHONPATH=$PYTHONPATH:/opt
ENV PATH=$PATH:/opt/openbabel/install/bin
ENV PATH=$PATH:/opt/openbabel/install/include
ENV PATH=$PATH:/opt/openbabel/install/share
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/openbabel/install/lib
ENV PATH=$PATH:/opt/openbabel/install/include/openbabel3
RUN ln -s /opt/openbabel/install/include/openbabel3 /usr/local/include/openbabel3
RUN ln -s /opt/openbabel/install/lib/libopenbabel.so /usr/local/lib/libopenbabel.so
RUN scp -r /opt/openbabel/install/lib/python3.10/site-packages/openbabel /usr/local/lib/python3.10/dist-packages


# Install XTB from Grimme-lab
WORKDIR /opt
RUN git clone https://github.com/grimme-lab/xtb.git                         
RUN cd /opt/xtb                                                             && \
    cmake -B build -DCMAKE_C_COMPILER=gcc -DCMAKE_FORTRAN_COMPILER=gfortran    \
    -DCMAKE_INSTALL_PREFIX=/opt/xtb/install -DCMAKE_BUILD_TYPE=Release      && \
    make -C build                                                           && \
    make -C build install
ENV PATH=$PATH:/opt/xtb/install/bin
ENV PATH=$PATH:/opt/xtb/install/include
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/xtb/install/lib


# Install Architector from LANL
WORKDIR /opt
RUN git clone -b Secondary_Solvation_Shell https://github.com/lanl/Architector.git 
RUN cd /opt/Architector                                                     && \
    pip install .                                                         
RUN pip install executorlib

# Install MPI-ping-pong from OLCF
WORKDIR /opt
ENV MPI_HOME "/opt/mpich/install"
RUN git clone https://github.com/olcf-tutorials/MPI_ping_pong.git test_code 
RUN cd /opt/test_code/cpu                                                   && \
    make                                                                    
RUN cd /opt/test_code/cuda_staged                                           && \
    sed -i 's:-arch=sm_70:-arch=sm_80:g' Makefile                           && \
    sed -i 's:OMPI_DIR:MPI_HOME:g' Makefile                                 && \
    sed -i 's:-lmpi_ibm:-lmpi:g' Makefile                                   && \
    make                                                                   
RUN cd /opt/test_code/cuda_aware                                            && \
    sed -i 's:-arch=sm_70:-arch=sm_80:g' Makefile                           && \
    sed -i 's:OMPI_DIR:MPI_HOME:g' Makefile                                 && \
    sed -i 's:-lmpi_ibm:-lmpi:g' Makefile                                   && \
    make
ENV PATH=$PATH:/opt/test_code/cpu
ENV PATH=$PATH:/opt/test_code/cuda_staged
ENV PATH=$PATH:/opt/test_code/cuda_aware
RUN pip install flux-python
